service: graphql-test
provider:
  name: aws
  runtime: nodejs8.10

functions:
  graphql:
    handler: handler.graphql
    events:
    - http:
        path: graphql
        method: post
        cors: true

  graphiql:
    handler: handler.graphiql
    events:
    - http:
        path: graphql
        method: get
        cors: true

plugins:
  - serverless-offline
